# Generated by Django 3.2.9 on 2022-04-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('anime', 'anime'), ('sports', 'sports'), ('movies', 'movies'), ('fashion', 'fashion'), ('tech', 'tech'), ('entertainment', 'entertainment'), ('relationships', 'relationships'), ('government and Politics', 'government and politics'), ('food', 'food'), ('music', 'music')], max_length=100)),
                ('image1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='jpeg', keep_meta=True, null=True, quality=100, size=[320, 280], upload_to='profile_images')),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='jpeg', keep_meta=True, null=True, quality=100, size=[320, 280], upload_to='profile_images')),
                ('multile_option_selection', models.BooleanField(default=False)),
                ('expire', models.DateTimeField()),
                ('public', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_poll', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
