# Generated by Django 3.2.9 on 2022-04-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
