# Generated by Django 3.2.9 on 2022-04-21 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_poll_voter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll_Voter',
            new_name='Poll_Vote',
        ),
    ]
