# Generated by Django 3.2.9 on 2022-04-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_poll_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_option',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
