# Generated by Django 3.2.9 on 2022-04-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20220422_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='multile_option_selection',
            new_name='multiple_option_selection',
        ),
    ]
