# Generated by Django 3.2.9 on 2022-04-25 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0015_rename_multile_option_selection_poll_multiple_option_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polls', models.ManyToManyField(to='polls.Poll')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
