# Generated by Django 3.2.9 on 2022-04-08 10:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='C:\\Users\\acer\\django_projects\\pollaway/media/profile_images/default-image.jpg', force_format='jpeg', keep_meta=True, null=True, quality=0, size=[300, 210], upload_to='profile_images'),
        ),
    ]
