# Generated by Django 3.2.9 on 2022-05-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
